export const kRpcGet = Symbol('rpc get method')
export const kRpcSet = Symbol('rpc set method')
export const kRpcHandlers = Symbol('rpc handlers')
export const kDgramHandlers = Symbol('dgram handlers')
export const kBasePubCallbacks = Symbol('publish callbacks from base module')